site_name: IAW

nav:
    - Principal: index.md
    - Acerca de: about.md
    - Práctica-1: Práctica1.md
    - Práctica-2: Práctica2.md
    - Práctica-3: Práctica3.md

theme: 
  name: material
  palette:
    primary: cyan
    accent: purple