site_name: IAW

nav:
    - Principal: index.md
    - Acerca de: about.md
    - Práctica-1.1: Práctica1.1.md
    - Práctica-1.11: Práctica1.11.md
    - Práctica-5.4: Práctica5.4.md

theme: 
  name: material
  palette:
    primary: cyan
    accent: purple